//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigratorUnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MigratorUnitTests.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update ReadModel_Attestation set ColumnGo = &apos;&apos; where Status = &apos;1&apos;.
        /// </summary>
        internal static string ColumnNameContainsGo {
            get {
                return ResourceManager.GetString("ColumnNameContainsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete From[dbo].[MigrationsJournal] /* go */ where scriptnumber &gt; 1 and scriptnumber&lt; 74
        ///Update Table1 set Col1 = &apos;val1&apos;.
        /// </summary>
        internal static string ContainsGoInAlternativeCommentStyle {
            get {
                return ResourceManager.GetString("ContainsGoInAlternativeCommentStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Remove go blah
        ///Delete From[dbo].[MigrationsJournal] where scriptnumber &gt; 1 and scriptnumber&lt; 74.
        /// </summary>
        internal static string ContainsGoInComment {
            get {
                return ResourceManager.GetString("ContainsGoInComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW[dbo].[EventFlowDebug]
        ///AS
        ///  SELECT
        ///dbo.EventFlow.GlobalSequenceNumber,
        ///EventId
        ///FROM
        ///	dbo.EventFlow
        ///	CROSS APPLY OPENJSON(dbo.EventFlow.Metadata)
        ///		WITH(
        ///			EventName NVARCHAR(500) &apos;$.event_name&apos;, 
        ///			EventVersion INTEGER &apos;$.event_version&apos;
        ///		).
        /// </summary>
        internal static string DoesNotContainGo {
            get {
                return ResourceManager.GetString("DoesNotContainGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select* from table1 where col = &apos;whatever&apos;
        ///go
        ///IF OBJECT_ID(&apos;EventFlowDebug&apos;, &apos;V&apos;) IS NOT NULL
        ///    DROP VIEW[dbo].[EventFlowDebug].
        /// </summary>
        internal static string FirstCase {
            get {
                return ResourceManager.GetString("FirstCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select* from table1 where col = &apos;whatever&apos;
        ///.
        /// </summary>
        internal static string FirstCaseFirstResult {
            get {
                return ResourceManager.GetString("FirstCaseFirstResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///IF OBJECT_ID(&apos;EventFlowDebug&apos;, &apos;V&apos;) IS NOT NULL
        ///    DROP VIEW[dbo].[EventFlowDebug].
        /// </summary>
        internal static string FirstCaseSecondResult {
            get {
                return ResourceManager.GetString("FirstCaseSecondResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Table1 set Col1 = &apos;val1&apos;
        ///go.
        /// </summary>
        internal static string GoIsLastWordNoNewline {
            get {
                return ResourceManager.GetString("GoIsLastWordNoNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Table1 set Col1 = &apos;val1&apos;
        ///.
        /// </summary>
        internal static string GoIsLastWordNoNewlineResult {
            get {
                return ResourceManager.GetString("GoIsLastWordNoNewlineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Table1 set Col1 = &apos;val1&apos;
        ///go.
        /// </summary>
        internal static string GoIsLastWordWithNewline {
            get {
                return ResourceManager.GetString("GoIsLastWordWithNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Table1 set Col1 = &apos;val1&apos;
        ///.
        /// </summary>
        internal static string GoIsLastWordWithNewlineResult {
            get {
                return ResourceManager.GetString("GoIsLastWordWithNewlineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select* from table1 where col = &apos;whatever&apos;
        ///GO-- comment
        ///update table1 set col1 = &apos;x&apos;.
        /// </summary>
        internal static string SecondCase {
            get {
                return ResourceManager.GetString("SecondCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select* from table1 where col = &apos;whatever&apos;
        ///.
        /// </summary>
        internal static string SecondCaseFirstResult {
            get {
                return ResourceManager.GetString("SecondCaseFirstResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- comment
        ///update table1 set col1 = &apos;x&apos;.
        /// </summary>
        internal static string SecondCaseSecondResult {
            get {
                return ResourceManager.GetString("SecondCaseSecondResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW[dbo].[EventFlowDebug]
        ///AS
        ///  SELECT
        ///dbo.EventFlow.GlobalSequenceNumber,
        ///EventId
        ///FROM
        ///	dbo.EventFlow
        ///	CROSS APPLY OPENJSON(dbo.EventFlow.Metadata)
        ///		WITH(
        ///			EventName NVARCHAR(500) &apos;$.event_name&apos;, 
        ///			EventVersion INTEGER &apos;$.event_version&apos;
        ///		)
        ///Go
        ///-- Remove old journal entries for non-CI environments, except for first one(which will represent this entry) so it appears as applied
        ///Delete From[dbo].[MigrationsJournal] where scriptnumber &gt; 1 and scriptnumber&lt; 74.
        /// </summary>
        internal static string ThirdCase {
            get {
                return ResourceManager.GetString("ThirdCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW[dbo].[EventFlowDebug]
        ///AS
        ///  SELECT
        ///dbo.EventFlow.GlobalSequenceNumber,
        ///EventId
        ///FROM
        ///	dbo.EventFlow
        ///	CROSS APPLY OPENJSON(dbo.EventFlow.Metadata)
        ///		WITH(
        ///			EventName NVARCHAR(500) &apos;$.event_name&apos;, 
        ///			EventVersion INTEGER &apos;$.event_version&apos;
        ///		)
        ///.
        /// </summary>
        internal static string ThirdCaseFirstResult {
            get {
                return ResourceManager.GetString("ThirdCaseFirstResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- Remove old journal entries for non-CI environments, except for first one(which will represent this entry) so it appears as applied
        ///Delete From[dbo].[MigrationsJournal] where scriptnumber &gt; 1 and scriptnumber&lt; 74.
        /// </summary>
        internal static string ThirdCaseSecondResult {
            get {
                return ResourceManager.GetString("ThirdCaseSecondResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select* from table1 where col = &apos;whatever&apos;
        ///go
        ///IF OBJECT_ID(&apos;EventFlowDebug&apos;, &apos;V&apos;) IS NOT NULL
        ///    DROP VIEW[dbo].[EventFlowDebug].
        /// </summary>
        internal static string UnixLineEnding {
            get {
                return ResourceManager.GetString("UnixLineEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select* from table1 where col = &apos;whatever&apos;
        ///.
        /// </summary>
        internal static string UnixLineEndingFirstResult {
            get {
                return ResourceManager.GetString("UnixLineEndingFirstResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///IF OBJECT_ID(&apos;EventFlowDebug&apos;, &apos;V&apos;) IS NOT NULL
        ///    DROP VIEW[dbo].[EventFlowDebug].
        /// </summary>
        internal static string UnixLineEndingSecondResult {
            get {
                return ResourceManager.GetString("UnixLineEndingSecondResult", resourceCulture);
            }
        }
    }
}
